POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "sergio@gmail.com",
    "password": "sergio123"
}

###
GET http://localhost:3000/users/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaXNfYWRtaW4iOjEsImlhdCI6MTczNDAyMzU2NiwiZXhwIjoxNzM0MDIzODY2fQ.jpT0NE27HPtmfHXf9uSDjEUqU7jXqtzji860xL-Ot_A