GET http://localhost:3000/users/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM0MDIxNTI4LCJleHAiOjE3MzQwMjE4Mjh9.mLATBZ0zaP8qhET0W9E7QhENDnF6I6lWAl-BEOWQuxo

###
GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM0MDIzMTU1LCJleHAiOjE3MzQwMjM0NTV9.5MfDt7ymf7zoQajwvckHE-eKPMLtjEpe02qBf5kgPI4

###
GET http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM0MDIzMTU1LCJleHAiOjE3MzQwMjM0NTV9.5MfDt7ymf7zoQajwvckHE-eKPMLtjEpe02qBf5kgPI4
###

POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaXNfYWRtaW4iOjEsImlhdCI6MTczNDAyMzU2NiwiZXhwIjoxNzM0MDIzODY2fQ.jpT0NE27HPtmfHXf9uSDjEUqU7jXqtzji860xL-Ot_A

{
    "first_name": "Martin",
    "last_name": "Osorio",
    "email": "martin@gmail.com",
    "password": "martin123"
}

###

PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "first_name": "Irivng",
    "last_name": "Cervantes",
    "email": "irvingcervantes@gmail.com"
}

###

DELETE http://localhost:3000/users/2