GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "first_name": "Sergo",
    "last_name": "Cervantes",
    "email": "sergio@gmail.com",
    "password": "sergio123"
}