### Obtener todos los clientes
GET http://localhost:3000/clients
Content-Type: application/json

###

### Obtener un cliente por RFC
GET http://localhost:3000/clients/A12345

###

### Agregar un nuevo cliente
POST http://localhost:3000/clients
Content-Type: application/json

{
  "rfc": "A12345",
  "first_name": "Bryan",
  "last_name": "Morales",
  "birth_date": "2004-08-10",
  "gender": "M",
  "phone_number": "2871235678",
  "email": "bryan.morales@example.com",
  "address": "Colonia la piragua, Tuxtepec, México"
}

###

### Actualizar un cliente existente
PUT http://localhost:3000/clients/A12345
Content-Type: application/json

{
  "first_name": "Juan",
  "last_name": "Cervantes",
  "birth_date": "2004-01-01",
  "gender": "M",
  "phone_number": "1234567890",
  "email": "juan.cevantes@example.com",
  "address": "1234 Street Name"
}


### Eliminar un cliente
DELETE http://localhost:3000/clients/A12345


