### Obtener todos los productos (incluidos con stock 0)
GET http://localhost:3000/products
Content-Type: application/json

### Obtener productos con stock mayor a 0
GET http://localhost:3000/products/with-stock
Content-Type: application/json

### Obtener un producto por ID
GET http://localhost:3000/products/5 
Content-Type: application/json

### Agregar un nuevo producto
POST http://localhost:3000/products 
Content-Type: application/json

{
  "product": "Modelo especial 500ml",
  "description": "Cerveza modelo especial de 500 ml",
  "stock": 500,
  "measurement_unit": "liters",
  "price": 30.5,
  "discount": 5
}

### Actualizar un producto 
PUT http://localhost:3000/products/1 
Content-Type: application/json

{
  "product": "Updated Product",
  "description": "Updated product description.",
  "stock": 120,
  "measurement_unit": "unit",
  "price": 55.0,
  "discount": 15
}

### Eliminar un producto (marcar como inactivo)
DELETE http://localhost:3000/products/1
Content-Type: application/json
