GET http://localhost:3000/usuarios

### 
GET http://localhost:3000/usuarios/5

### 
POST http://localhost:3000/usuarios/ 
content-type: application/json

{
"nombre": "Irving", 
"apellidos": "Benitez", 
"email": "irvingenrique@gmail.com"
}
